// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbYfAsze6BqSxclqRd4G2o_nK8dB35J2A',
    appId: '1:726185954390:web:ff9e4c32a5e3e5a6d97ff7',
    messagingSenderId: '726185954390',
    projectId: 'myschool-am099',
    authDomain: 'myschool-am099.firebaseapp.com',
    storageBucket: 'myschool-am099.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAIMsZVdM0F9n6CjTBI1vtbH_nMwsb3_o',
    appId: '1:726185954390:android:37ed725b9dacb764d97ff7',
    messagingSenderId: '726185954390',
    projectId: 'myschool-am099',
    storageBucket: 'myschool-am099.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoTMkH31dgZeHSWm1b7jXOsz9y3jkXrG8',
    appId: '1:726185954390:ios:cd8315e1f44a997ad97ff7',
    messagingSenderId: '726185954390',
    projectId: 'myschool-am099',
    storageBucket: 'myschool-am099.appspot.com',
    iosClientId: '726185954390-5f7cbgafbbjadkfqfrvth04rkeedo9f6.apps.googleusercontent.com',
    iosBundleId: 'com.example.mySchoolApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoTMkH31dgZeHSWm1b7jXOsz9y3jkXrG8',
    appId: '1:726185954390:ios:cd8315e1f44a997ad97ff7',
    messagingSenderId: '726185954390',
    projectId: 'myschool-am099',
    storageBucket: 'myschool-am099.appspot.com',
    iosClientId: '726185954390-5f7cbgafbbjadkfqfrvth04rkeedo9f6.apps.googleusercontent.com',
    iosBundleId: 'com.example.mySchoolApp',
  );
}
